name: ChatPrefix
version: '${version}'
main: com.Hakuuu.chatPrefix.ChatPrefix
api-version: '1.21'
depend: [PlaceholderAPI, LuckPerms]
commands:
  titles:
    description: Change your title
    usage: /titles <title_name>
    aliases: [prefix, prefixes]
  titlecolor:
    description: Change your title color
    usage: /titlecolor <&codeTitle>
    aliases: [prefixcolor]
    permission: prefixes.use
    permission-message: "&cInsufficient Permission!"
  titlereload:
    description: Reload the Prefixes Plugin
    usage: /titlereload
    permission: prefixes.reload
    permission-message: "&cInsufficient Permission!"

permissions:
  prefixes.use:
    description: Allows players to open the title list and select a prefix.
    default: true
  prefixes.style.standard:
    description: Allows styling colors for non-synced titles (e.g., Member, Donors).
    default: false
  prefixes.change.others:
    description: Allows changing the title of other players.
    default: op
  prefixes.style.staff:
    description: Allows styling colors for Synced/Staff titles (Owner through JrHelper).
    default: false
  prefixes.chat.color:
    description: Allows the player to use color codes (&) in their chat messages.
    default: false
  prefixes.bypass:
    description: Allows styling any title regardless of restrictions or name matching.
    default: op
  prefixes.reload:
    description: Allows reloading the plugin configuration.
    default: op